version: '3.8'

services:
  postgres:
    image: postgres:14.1
    container_name: cm-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USERNAME}"
      - "POSTGRES_DB=${POSTGRES_DBNAME}"

  redis:
    image: redis:6.2
    container_name: cm-redis
    ports:
      - "6379:6379"

  ngrok:
    container_name: cm-ngrok
    image: ngrok/ngrok:alpine
    command:
      - "--config"
      - "/etc/ngrok.yml"
      - "start"
      - "interactions"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040